namespace TownOfUs
{
    public enum CustomRPC
    {
        SetRole = 100,
        SetModifier,
        SetCouple,
        SetAssassin,
        SetTarget,
        SetDefendant,
        SetGATarget,

        SetPhantom,
        CatchPhantom,

        SetHaunter,
        CatchHaunter,

        SetTraitor,
        TraitorSpawn,

        LoveWin,
        GlitchWin,
        JuggernautWin,
        ArsonistWin,
        PhantomWin,
        NobodyWins,
        PlaguebearerWin,
        PestilenceWin,
        WerewolfWin,
        SurvivorOnlyWin,
        MercenaryOnlyWin,
        VampireWin,
        FanaticsWin,

        JanitorClean,
        ScavengerClean,
        FixLights,
        EngineerFix,
        SetSwaps,
        Protect,
        MercProtect,
        AttemptSound,
        MercShield,
        Morph,
        Mine,
        Swoop,
        AltruistRevive,
        ImmortalRevive,
        ImmortalReviveNow,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        VigilanteKill,
        Vigilance,
        DoomsayerKill,
        FlashGrenade,
        Alert,
        Remember,
        BaitReport,
        Transport,
        SetUntransportable,
        Mediate,
        Vest,
        DonArmor,
        GAProtect,
        Blackmail,
        Infect,
        TurnPestilence,
        Disperse,
        Escape,
        Imitate,
        StartImitate,
        Plant,
        Bite,
        Reveal,
        Prosecute,
        Confess,
        Bless,
        Camouflage,
        Campaign,
        TurnMayor,
        Bodyguard,
        UpdateImitator,
        HunterStalk,
        HunterCatchPlayer,
        Retribution,
        Indoctrinate,
        FanaticConvert,
        Fortify,
        Hypnotise,
        Jail,
        Collect,

        BypassKill,
        BypassMultiKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,
        LawyerToJester,
        GAToSurv,

        Start,
        SyncCustomSettings,
        FixAnimation,
        SetPos,
        SetSettings,
        
        RemoveAllBodies,
        CheckMurder,

        SubmergedFixOxygen,

        ContentAddition
    }
}
